---

- hosts: vsfi
  remote_user: root
  tasks:
    - name: ping
      ping:
    
    - name: change hostname
      hostname: 
        name: "{{ vsfi_hostname }}"
        
    - name:  Setup motd
      template:
        src: motd.j2
        dest: /etc/motd
        mode: 0644
        owner: root